insert into customer(firstname, lastname, age) values ("alice", "kim", 25)
insert into customer(firstname, lastname, age) values ("bob", "kim", 25)
insert into customer(firstname, lastname, age) values ("charlie", "kim", 25)
insert into customer(firstname, lastname, age) values ("bob", "choi", 25)
insert into customer(firstname, lastname, age) values ("hoyeong", "cheon", 25)
insert into customer(firstname, lastname, age) values ("alice", "choi", 25)